[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 50
enableWebsocketCompression = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[runner]
fastReruns = true
magicEnabled = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"